---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096
  network:
    - ['forwarded_port', {guest: 8080, host: 8080, auto_correct: true}] # expose jira

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[jira]
