driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096
  network:
    # Allow access to the JIRA webui which is useful when troubleshooting
    - - forwarded_port
      - guest: 8080
        host: 8080
        auto_correct: true

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
  - name: centos-7.0
  - name: ubuntu-14.04
  - name: ubuntu-15.04
    attributes:
      postgresql:
        # postgresql cookbook doesn't support 15.04 yet.
        version: '9.4'
        enable_pgdg_apt: false

suites:
  - name: default
    run_list:
      - recipe[jira_test::default]
